### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Alf71** [pcaversaccio/mass-key-generation#1]
root@DESKTOP-111:/home/admin7/MASSKEY# ./gradlew assembleDist
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.ethereum:ethereumj-core:1.5.0-RELEASE.
     Required by:
         project :
      > Could not resolve org.ethereum:ethereumj-core:1.5.0-RELEASE.
         > Could not get resource 'https://dl.bintray.com/ethereum/maven/org/ethereum/ethereumj-core/1.5.0-RELEASE/ethereumj-core-1.5.0-RELEASE.pom'.
            > Could not GET 'https://dl.bintray.com/ethereum/maven/org/ethereum/ethereumj-core/1.5.0-RELEASE/ethereumj-core-1.5.0-RELEASE.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by pcaversaccio** [comment]
This repository is set to stale.
